In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline
import mpld3
mpld3.disable_notebook()
from tqdm import tqdm
from time import sleep
import scipy as sp

### For differential equations the form is ay''+by'+cy=dt
#### The intial for x1 = a_1 , x2 = a_2

In [3]:
def number_of_steps(to, tf, h):
    n = (tf-to)/h
    return n

In [24]:
def steps_time(to , tf, h):
    t = []
    n = []
    for i in range(int(number_of_steps(to, tf, h))+1):
        t.append(i*h+to)
        n.append(int(i))
    return t , n

In [25]:
def x_1_value(h, t,  x_1, x_2):
    return x_1 + h*x_2

### You  can adjust the formula for X_2 to modify to fit the formula of expects, here is a dt formula but you can easily change it

In [26]:
def x_2_value(h, t, x_1, x_2, a,b,c,d):
    return x_2 + h*((d*t-b*x_2-c*x_1)/a)

### Method input is time intial, time final, step size, y(t) intial, y'(t) intial,

In [148]:
def eulers_method(to, tf, h ,a_1, a_2, a,b,c,d):
    x1list = []
    x2list = []
    t = steps_time(to , tf, h)[0]
    n = steps_time(to, tf, h)[1]
    x1list.append(a_1)
    x2list.append(a_2)

    for i in range(len(n)):
        x1 = x_1_value(h, t[i], x1list[i], x2list[i])
        x1list.append(x1)
        
        x2 = x_2_value(h, t[i], x1list[i], x2list[i], a,b,c,d)
        x2list.append(x2)
        
    return n, t ,x1list, x2list

In [153]:
df = pd.DataFrame(eulers_method(0,12,0.5,2,-1,1,-3,2, 1),['Step','Time','x1','x2'])

In [154]:
df = df.T
df

    Step  Time            x1            x2
0    0.0   0.0  2.000000e+00 -1.000000e+00
1    1.0   0.5  1.500000e+00 -4.500000e+00
2    2.0   1.0 -7.500000e-01 -1.262500e+01
3    3.0   1.5 -7.062500e+00 -3.031250e+01
4    4.0   2.0 -2.221875e+01 -6.759375e+01
5    5.0   2.5 -5.601562e+01 -1.447656e+02
6    6.0   3.0 -1.283984e+02 -3.027734e+02
7    7.0   3.5 -2.797852e+02 -6.240352e+02
8    8.0   4.0 -5.918027e+02 -1.274178e+03
9    9.0   4.5 -1.228892e+03 -2.585642e+03
10  10.0   5.0 -2.521712e+03 -5.225087e+03
11  11.0   5.5 -5.134256e+03 -1.052851e+04
12  12.0   6.0 -1.039851e+04 -2.117188e+04
13  13.0   6.5 -2.098445e+04 -4.251320e+04
14  14.0   7.0 -4.224105e+04 -8.527743e+04
15  15.0   7.5 -8.487977e+04 -1.709280e+05
16  16.0   8.0 -1.703438e+05 -3.424121e+05
17  17.0   8.5 -3.415498e+05 -6.856546e+05
18  18.0   9.0 -6.843771e+05 -1.372551e+06
19  19.0   9.5 -1.370652e+06 -2.746959e+06
20  20.0  10.0 -2.744132e+06 -5.496699e+06
21  21.0  10.5 -5.492481e+06 -1.099757e+07
22  22.0  11.0 -1.099126e+07 -2.200138e+07
23  23.0  11.5 -2.199195e+07 -4.401212e+07
24  24.0  12.0 -4.399801e+07 -8.803828e+07
25   NaN   NaN -8.801716e+07 -1.760976e+08